### ISSUE TITLE
Support multiple commands per language

### ISSUE THREAD

**Issue by OlegAlexander** [Vehmloewff/custom-format#9]
Hello and thank you for creating `custom-format`!

I want to run one formatter after another in Haskell. Something like this:

```json
{
    "custom-format.formatters": [
        {
            "language": "haskell",
            "commands": [
                "haskell-formatter-1 $FILE",
                "haskell-formatter-2 $FILE"
            ]
        }
    ]
}
```

Do you know if this is possible currently? And if not, would it be possible to add this feature? 

Thank you!

**Comment by Vehmloewff** [comment]
Hello @OlegAlexander! Sorry this issue slipped off my radar until now!

You should be able to pipe the output of the first formatter into the input of the second formatter:

```json
"custom-format.formatters": [
    {
        "language": "haskell",
        "command": "bash -c \"haskell-formatter-1 $FILE | haskell-formatter-2 $FILE\""
    }
]
```

Testing this, however, I realize that the tool is splitting arguments incorrectly (#10), for which a workaround is to create a script to do the piping instead of providing the code inline with `-c`:

```sh
# script.sh

haskell-formatter-1 $1 | haskell-formatter-2 $1
```

```jsonc
// settings.json
{
    // ...
    "custom-format.formatters": [
        {
            "language": "haskell",
            "command": "bash script.sh $FILE"
        }
    ],
}
```

For this to work, though, it is important that the formatters actually read the code to be formatted from `stdin` instead of `$FILE`. If your particular formatters are not configured to read from `stdin`, passing `/dev/stdin` as the file will probably give them the nudge they need.

Let me know if this works!!

**Comment by OlegAlexander** [comment]
Thank you for your detailed reply. I'll try your suggestion, and I'm almost sure it will work, so I will close the issue and reopen it only if it doesn't work. Thanks!
